# Generated by Django 5.2.1 on 2025-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limit',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
