# Generated by Django 5.2.1 on 2025-05-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_limit_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limit',
            name='month',
        ),
    ]
